os: linux
 
language: android
 
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
 
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.2
  - android-30 # match your targetVersion
 
jdk: oraclejdk8
 
sudo: false
 
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-droid


cache:
  directories:
  - "$HOME/.pub-cache"
 
before_install:
  - yes | sdkmanager "platforms;android-30"
 
install:
- git clone https://github.com/flutter/flutter.git -b stable --depth 1
- export PATH=./flutter/bin:$PATH
- flutter doctor

script:
- flutter packages get
- /bin/cp -rf flutter_packages/ flutter/packages/
- rm -rf flutter/packages/flutter/lib/src/widgets/navigator.dart
- cp flutter_packages/flutter/lib/src/widgets/navigator.dart flutter/packages/flutter/lib/src/widgets/navigator.dart
# - flutter analyze --no-pub --no-current-package lib/ test/
# - flutter test --no-pub --no-sound-null-safety test/

env:
 - BUILD_TIME=$(date +'%Y%m%d%H%M%S') APK_NAME="${TRAVIS_TAG}_${BUILD_TIME}_OneMC.apk"
 
before_deploy:
- flutter build apk --no-sound-null-safety
- mv build/app/outputs/apk/release/app-release.apk $APK_NAME

deploy:
  provider: releases
  api_key:
    secure: "nSwUpG5GjCNspGkuhGVIprCrv/h5N/dSQGsG2HY3RAWr7heBBC1d3rW03IDocmYCMiH9XHLoiYeLKhnrzqfhS8pME4XV+sL+nfxCB3R2bo2U3BvsLDPunlliREWgYzEhppdyIQ3CFQZPXWgvTUp2dHATVYhBNGavvqlDj9JWRF5Y5vgPZrlhruyuwzAUxuix/dlA4th2ay7ECmZBt6H69Tg0BunUuZgvihhNryDavvhsbzHzIiknxgCCGwdX16mHfIKbvkcJvb7wmh7R0rS3oOx+lMhrmEnxNbayo3x2LH8ZqoE0W4rl5kV45wqkCk8hexZnSe462u5VwTiwJSqU1fMhas1cLnNLIzffAl2dj+kwCgf38U7F5RFf+9k64gN93NQk2odj1CFGrDQ5pocI4U2j50SqYnccsgkr1AYfb9TvaRMputpI5tc/8hi4BLScMNUgc/E8BocscP6r3zeGhxgYModLeLFhGSMjZ1wRlLuc2hanhvaBbpb7iYpijE5HF0LHPnL0eFy/+oIAlGVXjfvGPucEWx/2GqBB/N/YYjsp/BfC4wF9fpkhYwNNBFS29/bDasb+lhIT1ZjZxnYRjDMPXzE7xYiIO5Kb/0eydPghTkTs+7j/pMmy4YXx0redWSKXI1NI/y4ycCJ8+k/C2bnC0rnCpl7s8DUa6VC3sio="
  file: $APK_NAME
  skip_cleanup: true
  overwrite: true
  on:
    repo: htser/onemc_app
    branch: main
#    condition: $TRAVIS_TAG =~ /^release-v\d+\.\d+\.\d+/ # when tag match release-vx.x.x, then push a relase and upload apk.
