os: linux
 
language: android
 
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
 
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.2
  - android-30 # match your targetVersion
 
jdk: oraclejdk8
 
sudo: false
 
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-droid


cache:
  directories:
  - "$HOME/.pub-cache"
 
before_install:
  - yes | sdkmanager "platforms;android-30"
 
install:
- git clone https://github.com/flutter/flutter.git -b stable --depth 1
- export PATH=./flutter/bin:$PATH
- flutter doctor

script:
- flutter packages get
- /bin/cp -rf flutter_packages/ flutter/packages/
- rm -rf flutter/packages/flutter/lib/src/widgets/navigator.dart
- cp flutter_packages/flutter/lib/src/widgets/navigator.dart flutter/packages/flutter/lib/src/widgets/navigator.dart
# - flutter analyze --no-pub --no-current-package lib/ test/
# - flutter test --no-pub --no-sound-null-safety test/

env:
 - BUILD_TIME=$(date +'%Y%m%d%H%M%S') APK_NAME="${TRAVIS_TAG}_${BUILD_TIME}_OneMC.apk"
 
before_deploy:
- flutter build apk --no-sound-null-safety
- mv build/app/outputs/apk/release/app-release.apk $APK_NAME

deploy:
  provider: releases
  api_key:
    secure: "yspGg/FbPI4zken6dTKKDV9E+8g2NVDPDQCT/UI771yytMCyZ4UaBJGMbbOZLqF48ENeMa17GdaNB8zMdZO/4ZtvNy6vRWF/5YsNbwl2SV050zyOSRHkf0GftP4Qc/e4eQhz2ROi4U3cUGYA6QYjnbls3AyiKFANp1vz1tDeBCh3imKIxZjO8TJQYvBYfDvrXNoI8yRe3Bih/P/TWWdhCPfo60NsUr5G2YJkPilOaRXFMVIQiE5OC9RsFZH8wgKztVxY7j2W4XXsgAQ0IbnwVGFJV9xaEsFdPA/ZJYIW0M8xrZxCNok0XWDplVGElUa0nQALKSg+Zkr4/ehjd0wSuH70RW9F4xm2iMF91TIO1+dR62hv+QinWQkDGl7pgFV+BagW0ohzaB50w+8mJ4Kg/23pM2rhtgqTQig1DMXButZwD1k0Y7PXwgUmBq5GiCz8UPs5x2919rvS4lDB9V5DU/0KlbxGiQnYarn1zkD2N6EYNkJYIeOhNP/iVc/L6I61SzeWPEHZdKzsba4bAw0WO1I8drt5l8V+oAjK7VbzKHOGQfAJULO3kivUyDg6qGZa+B0vEpKfL3M7clXUMmqjNPKIeAd7XqAekxzPozcQJasKfMx7/XEPPw48w1E96sonZlgLxSur7G+ccbkWEs1sFNFF7NBJORpQCZ27cRzEs60="
  file: $APK_NAME
  skip_cleanup: true
  overwrite: true
  on:
    repo: htser/onemc_app
    branch: main
#    condition: $TRAVIS_TAG =~ /^release-v\d+\.\d+\.\d+/ # when tag match release-vx.x.x, then push a relase and upload apk.


